import pytest
import os
import sys
import numpy as np
# DLL paths and the pythonnet runtime are initialized once in tests/conftest.py.
import clr

clr.AddReference("VM.Image")
import VM.Image.Compression as VMComp
import System
from System.IO import StringReader
from System.Xml.Serialization import XmlSerializer

from videometer.hips_core import HipsImage, QuantizationParameters

def test_xml_serialization_fidelity():
    """
    PHASE 3 VERIFICATION:
    Verifies that the quantization XML generated by Python is 100% 
    parseable by the legacy C# XmlSerializer.
    
    Requirements verified:
    1. utf-16 declaration is present.
    2. Namespaces (xsd, xsi) are correct.
    3. Parameters (Q, Q_Min, Q_Max) are attributes.
    4. Numeric values are correctly parsed back in .NET.
    """
    img = HipsImage()
    img._quantization_parameters = [
        QuantizationParameters(Q=12, Q_Min=0.0, Q_Max=120.0),
        QuantizationParameters(Q=8, Q_Min=-1.0, Q_Max=1.0)
    ]
    
    # 1. Generate XML string in Python
    xml_str = img._generate_quantization_xml()
    
    # High-level string checks
    assert 'encoding="utf-16"' in xml_str
    assert 'xmlns:xsd' in xml_str
    assert 'xmlns:xsi' in xml_str
    assert 'Q_Min="0"' in xml_str or 'Q_Min="0.0"' in xml_str
    
    # 2. Verify with real .NET XmlSerializer
    try:
        # Resolve the C# Array Type for QuantizationParameters
        qp_type = clr.GetClrType(VMComp.QuantizationParameters)
        arr_type = System.Type.GetType("VM.Image.Compression.QuantizationParameters[], VM.Image")
        if arr_type is None:
            # Fallback for different assembly versions
            arr_type = System.Array[VMComp.QuantizationParameters].GetType()
            
        serializer = XmlSerializer(arr_type)
        reader = StringReader(xml_str)
        dotnet_array = serializer.Deserialize(reader)
        
        # 3. Assert values match
        assert len(dotnet_array) == 2
        
        # Band 0: 12-bit [0, 120]
        assert dotnet_array[0].Q == 12
        assert pytest.approx(float(dotnet_array[0].Q_Min)) == 0.0
        assert pytest.approx(float(dotnet_array[0].Q_Max)) == 120.0
        
        # Band 1: 8-bit [-1, 1]
        assert dotnet_array[1].Q == 8
        assert pytest.approx(float(dotnet_array[1].Q_Min)) == -1.0
        assert pytest.approx(float(dotnet_array[1].Q_Max)) == 1.0
        
    except Exception as e:
        pytest.fail(f"XML Serialization Fidelity Check FAILED: {e}\nGenerated XML:\n{xml_str}")

if __name__ == "__main__":
    pytest.main([__file__])
