import pytest
import os
import sys
import numpy as np
import pythonnet
if pythonnet.get_runtime_info() is None:
    pythonnet.load("coreclr")
import clr

# Initialize DLL paths for legacy Oracle
VMPATH = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
VMPATH_SRC = os.path.join(VMPATH, "src", "videometer")
IPP_PATH = os.path.join(VMPATH_SRC, "DLLs", "IPP2019Update1", "intel64")
DLL_PATH = os.path.join(VMPATH_SRC, "DLLs", "VM")

os.environ["PATH"] = IPP_PATH + ";" + os.environ["PATH"]
if sys.platform == "win32" and hasattr(os, "add_dll_directory"):
    os.add_dll_directory(IPP_PATH)
    os.add_dll_directory(DLL_PATH)
sys.path.append(DLL_PATH)

clr.AddReference("VM.Image")
import VM.Image.Compression as VMComp
import System
from System.IO import StringReader
from System.Xml.Serialization import XmlSerializer

from videometer.hips_core import HipsImage, QuantificationParameters

def test_xml_serialization_fidelity():
    """
    PHASE 3 VERIFICATION:
    Verifies that the quantization XML generated by Python is 100% 
    parseable by the legacy C# XmlSerializer.
    
    Requirements verified:
    1. utf-16 declaration is present.
    2. Namespaces (xsd, xsi) are correct.
    3. Parameters (Q, Q_Min, Q_Max) are attributes.
    4. Numeric values are correctly parsed back in .NET.
    """
    img = HipsImage()
    img._quantization_parameters = [
        QuantificationParameters(Q=12, Q_Min=0.0, Q_Max=120.0),
        QuantificationParameters(Q=8, Q_Min=-1.0, Q_Max=1.0)
    ]
    
    # 1. Generate XML string in Python
    xml_str = img._generate_quantization_xml()
    
    # High-level string checks
    assert 'encoding="utf-16"' in xml_str
    assert 'xmlns:xsd' in xml_str
    assert 'xmlns:xsi' in xml_str
    assert 'Q_Min="0"' in xml_str or 'Q_Min="0.0"' in xml_str
    
    # 2. Verify with real .NET XmlSerializer
    try:
        # Resolve the C# Array Type for QuantificationParameters
        qp_type = clr.GetClrType(VMComp.QuantificationParameters)
        arr_type = System.Type.GetType("VM.Image.Compression.QuantificationParameters[], VM.Image")
        if arr_type is None:
            # Fallback for different assembly versions
            arr_type = System.Array[VMComp.QuantificationParameters].GetType()
            
        serializer = XmlSerializer(arr_type)
        reader = StringReader(xml_str)
        dotnet_array = serializer.Deserialize(reader)
        
        # 3. Assert values match
        assert len(dotnet_array) == 2
        
        # Band 0: 12-bit [0, 120]
        assert dotnet_array[0].Q == 12
        assert pytest.approx(float(dotnet_array[0].Q_Min)) == 0.0
        assert pytest.approx(float(dotnet_array[0].Q_Max)) == 120.0
        
        # Band 1: 8-bit [-1, 1]
        assert dotnet_array[1].Q == 8
        assert pytest.approx(float(dotnet_array[1].Q_Min)) == -1.0
        assert pytest.approx(float(dotnet_array[1].Q_Max)) == 1.0
        
    except Exception as e:
        pytest.fail(f"XML Serialization Fidelity Check FAILED: {e}\nGenerated XML:\n{xml_str}")

if __name__ == "__main__":
    pytest.main([__file__])
